/**
  ******************************************************************************************************************
  * @file    boule.c 
  * @author  PCo     IUT Informatique La Rochelle
  * @version v1.2
  * @date    2021
  * @modification
  * @brief   définitions pour la description du bitmap d'une boule
  ******************************************************************************************************************/

#include "ext_globales.h"
#include "GLCD_Config.h"
#include "boule.h"


const unsigned short bmpBoule[HAUTEUR_BOULE*LARGEUR_BOULE]={
	GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,
	GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,
	GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,
	GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,
	GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,
	GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,
	GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,
	GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_YELLOW,GLCD_COLOR_BLACK ,GLCD_COLOR_BLACK ,
};

const unsigned short bmpEraseBoule[HAUTEUR_BOULE*LARGEUR_BOULE]={
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
};

const unsigned short bmpPowerUp[HAUTEUR_BOULE*LARGEUR_BOULE]={
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_RED  ,GLCD_COLOR_RED  ,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_RED  ,GLCD_COLOR_RED  ,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_RED  ,GLCD_COLOR_RED  ,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_RED  ,GLCD_COLOR_RED  ,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_GREEN,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
	GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_GREEN,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,GLCD_COLOR_BLACK,
};
